version: "3"

services:
  nginx:
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
  ################# React Front - Node Backend########################
  react-front:
    build:
      dockerfile: dev.dockerfile
      context: ReactFront
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./ReactFront:/usr/app
    command: ["npm", "run", "start"]

  ################# Node BackEnd########################  
  node-back:
    build:
      context: ./node_rest_api
      dockerfile: dev.dockerfile
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./node_rest_api:/usr/app
    command: ["npm", "run", "dev"]

  ################# React Front - Golang Backend########################  
  react-front-golang:
    build:
      dockerfile: dev.dockerfile
      context: ReactFrontGolang
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./ReactFrontGolang:/usr/app
    #ports:
    #  - "3002"  
    command: ["npm", "run", "start"]  

  ################# Golang Backend########################    
  golang-back:
    build:
      context: ./go_rest_api
      dockerfile: dev.dockerfile
    env_file:
      - .env
    volumes:
      - ./golang:/root
    depends_on:
      - postgres
    command: ["go", "run", "main.go"]

  ################# Postgre ########################      
  postgres:
    build:
      context: ./PostgresDb
      dockerfile: dev.dockerfile
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./PostgresDb/dev/data:/var/lib/postgresql/data
